server:
  port: 8080

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.cgenh.springCloud.entities       # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: springMVC_Activiti
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: ${project.jdbc.driver}               # mysql驱动包
    url: ${project.jdbc.url}                                # 数据库名称
    username: ${project.jdbc.username}
    password: ${project.jdbc.password}
    dbcp2:
      min-idle: ${project.jdbc.min-idle}                    # 数据库连接池的最小维持连接数
      initial-size: ${project.jdbc.initial-size}            # 初始化连接数
      max-total: ${project.jdbc.max-total}                  # 最大连接数
      max-wait-millis: ${project.jdbc.max-wait-millis}      # 等待连接获取的最大超时时间
